### ISSUE TITLE
Waiting for VSCode theme

### ISSUE THREAD

**Issue by glmn** [gbgabo/wildberries-nextjs#2]
Really like it! Hope you will make it ;)

**Comment by gbgabo** [comment]
Hey @glmn! I'm definitely making it!

Expect it to be available within the next two weeks, after finishing my study semester.

The official port will be based on my current [vscodium config](https://github.com/gbgabo/dotfiles/blob/master/config/vscodium-settings.json). Now its scrambled with my other vscode settings, but if you want no wait, you can fiddle with it to install for your client.

Currently it works by installing an extension in VScodium called theme generator. The port will be implemented to not need that. 

привет из Бразилии! 🇧🇷

**Comment by gbgabo** [comment]
Hello again, @glmn

I just finished publishing the theme for vscode.

I added a variants for the ones who prefer darker tones, any opinions are welcome!

Hope you like it!

**Comment by glmn** [comment]
Looks very good! Thank you!
